artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/ananthapadmanabhan-o/BSD100/archive/refs/heads/main.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  local_data_source_path: artifacts/data_ingestion/BSD100-main
  local_input_feature_file: artifacts/data_transformation/input_features.pkl
  local_output_feature_file: artifacts/data_transformation/output_features.pkl

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.pkl
  updated_base_model_path: artifacts/base_model/base_model_updated.pkl
  
training:
  root_dir: artifacts/training
  base_model_path: artifacts/base_model/base_model.pkl
  trained_model_path: artifacts/training/trained_model.pkl
  local_input_feature_file: artifacts/data_transformation/input_features.pkl
  local_output_feature_file: artifacts/data_transformation/output_features.pkl
